version: '3.8'

services:
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: indentitydb
    environment:
      SA_PASSWORD: 'a2601197'
      ACCEPT_EULA: "Y"
    volumes:
      - identity_sqlserver_data:/var/opt/mssql
    restart: always
    ports:
      - "1436:1433"
        
volumes:
  identity_sqlserver_data:
    external: false
      